/* eslint-disable max-len */
export const texto1 = [
  { text: '1-Introdução:', bold: true },
  { text: '\nDescarga atmosférica:', bold: true },
  'Descarga elétrica de origem atmosférica entre uma nuvem e a terra ou entre nuvens, consistindo em um ou mais impulsos de vários quiloampères.',
  { text: '\nRaio:', bold: true },
  'Um dos impulsos elétricos de uma descarga atmosférica para a terra.',
  { text: '\nPonto de impacto::', bold: true },
  'Ponto onde uma descarga atmosférica atinge a terra, uma estrutura ou o sistema de proteção contra descargas atmosféricas.',
  { text: '\nVolume a proteger:', bold: true },
  'Volume de uma estrutura ou de uma região que requer proteção contra os efeitos das descargas atmosféricas conforme esta Norma.',
  { text: '\nSistema de proteção contra descargas atmosféricas (SPDA):', bold: true },
  'Sistema completo destinado a proteger uma estrutura contra os efeitos das descargas atmosféricas. É composto de um sistema externo e de um sistema interno de proteção.',
  { text: '\nSistema externo de proteção contra descargas atmosféricas:', bold: true },
  'Sistema que consiste em subsistema de captores, subsistema de condutores de descida e subsistema de aterramento.',
  { text: '\nSistema interno de proteção contra descargas atmosféricas:', bold: true },
  'Conjunto de dispositivos que reduzem os efeitos elétricos e magnéticos da corrente de descarga atmosférica dentro do volume a proteger.',
  { text: '\nLigação eqüipotencial:', bold: true },
  'Ligação entre o SPDA e as instalações metálicas, destinada a reduzir as diferenças de potencial causadas pela corrente de descarga atmosférica.',
  { text: '\nSubsistema captor (ou simplesmente captor):', bold: true },
  'Parte do SPDA destinada a interceptar as descargas atmosféricas.',
  { text: '\nSubsistema de descida:', bold: true },
  'Parte do SPDA destinada a conduzir a corrente de descarga atmosférica desde o subsistema captor até o subsistema de aterramento.',
];

export const texto2 = [
  { text: 'Subsistema de aterramento: ', bold: true },
  'Parte do SPDA destinada a conduzir e a dispersar a corrente de descarga atmosférica na terra.',
  { text: '\nEletrodo de aterramento: ', bold: true },
  'Elemento ou conjunto de elementos do subsistema de aterramento que assegura o contato elétrico com o solo e dispersa a corrente de descarga atmosférica na terra.',
  { text: '\nEletrodo de aterramento em anel: ', bold: true },
  'Eletrodo de aterramento formando um anel fechado em volta da estrutura.',
  { text: '\nEletrodo de aterramento de fundação: ', bold: true },
  'Eletrodo de aterramento embutido nas fundações da estrutura.',
  { text: '\nResistência de aterramento de um eletrocomodo: ', bold: true },
  'Relação entre a tensão medida entre o eletrodo e o terra remoto e a corrente injetada no eletrodo.',
  { text: '\nTensão de eletrodo de aterramento: ', bold: true },
  'Diferença de potencial entre o eletrodo de aterramento considerado e o terra de referência.',
  { text: '\nTerra de referência (de um eletrodo de aterramento): ', bold: true },
  'Região na terra, suficientemente afastada do eletrodo considerado, na qual a diferença de potencial entre dois pontos quaisquer, causada pela corrente nesse eletrodo, é desprezível.',
  { text: '\nComponente natural de um SPDA: ', bold: true },
  'Componente da estrutura que desempenha uma função de proteção contra descargas atmosféricas, mas não é instalado especificamente para este fim.',
  'NOTA Exemplos de componentes naturais:',
  '\na) Coberturas metálicas utilizadas como captores;',
  'b) Pilares metálicos ou armaduras de aço do concreto utilizadas como condutores de descida;',
  'c) Armaduras de aço das fundações utilizadas como eletrodos de aterramento.',
  { text: '\nInstalações metálicas: ', bold: true },
  'Elementos metálicos situados no volume a proteger, que podem constituir um trajeto da corrente de descarga atmosférica, tais  estruturas, tubulações, escadas, trilhos de elevadores, dutos de ventilação e ar-condicionado e armaduras de aço interligadas.',
];

export const texto3 = [
  { text: 'Massa (de um equipamento ou instalação): ', bold: true },
  'Conjunto das partes metálicas não destinadas a conduzir corrente, eletricamente interligadas, e isoladas das partes vivas, tais como invólucros de equipamentos elétricos.',
  { text: '\nLigação eqüipotencial (LEP ou TAP): ', bold: true },
  'Barra condutora onde se interligam ao SPDA as instalações metálicas, as massas e os sistemas elétricos de potência e de sinal.',
  'NOTA LEP = ligação eqüipotencial principal -TAP = terminal de aterramento principal.',
  { text: '\nCondutor de ligação eqüipotencial: ', bold: true },
  'Condutor de proteção que assegura uma ligação eqüipotencial.',
  { text: '\nArmaduras de aço (interligadas): ', bold: true },
  'Armaduras de aço embutidas numa estrutura de concreto, que asseguram continuidade elétrica para as correntes de descarga atmosférica.',
  { text: '\nCentelhamento perigoso: ', bold: true },
  'Descarga elétrica inadmissível, no interior ou na proximidade do volume a proteger, provocada pela corrente de descarga atmosférica.',
  { text: '\nDistância de segurança: ', bold: true },
  'Distância mínima entre dois elementos condutores no interior do volume a proteger, que impede o centelhamento perigoso entre eles.',
  { text: '\nDispositivo de proteção contra surtos - DPS: ', bold: true },
  'Dispositivo que é destinado a limitar sobretensões transitórias.',
  { text: '\nConexão de medição: ', bold: true },
  'Conexão instalada de modo a facilitar os ensaios e medições elétricas dos componentes de um SPDA.',
  { text: '\nSPDA externo isolado do volume a proteger: ', bold: true },
  'SPDA no qual os subsistemas de captores e os condutores de descida são instalados suficientemente afastados do volume a proteger, de modo a reduzir a probabilidade de centelhamento perigoso.',
  { text: '\nSPDA externo não isolado do volume a proteger: ', bold: true },
  'SPDA no qual os subsistemas de captores e de descida são instalados de modo que o trajeto da corrente de descarga atmosférica pode estar em contato com o volume a proteger.',
  { text: '\nEstruturas comuns: ', bold: true },
  'Estruturas utilizadas para fins comerciais, industriais, agrícolas, administrativos.',
];

export const texto4 = [
  { text: '2-Características Gerais:', bold: true },
  '\nUm SPDA projetado e instalado conforme a Norma não pode assegurar a proteção absoluta de uma estrutura, de pessoas e bens. Entretanto, a aplicação da mesma reduz de forma significativa os riscos de danos devidos às descargas atmosféricas.',
  '\nO acesso à terra e a utilização adequada das armaduras metálicas das fundações como eletrodo de aterramento podem não ser possíveis após o início dos trabalhos de construção. A natureza e a resistividade do solo devem ser consideradas no estágio inicial do projeto. Este parâmetro pode ser útil para dimensionar o subsistema de aterramento, que pode influenciar certos detalhes do projeto civil das fundações.',
  '\nO projeto, a instalação e os materiais utilizados em um SPDA devem atender plenamente a NBR5419 ABNT.',
  { text: '\n3-Captores naturais:', bold: true },
  '\nQuaisquer elementos condutores expostos, isto é, que do ponto de vista físico possam ser atingidos pelos raios, devem ser considerados como parte do SPDA.',
  '\nNotas',
  'Os elementos condutores expostos devem ser analisados para certificar se as suas características são compatíveis com os critérios estabelecidos para elementos captores.',
  'Exemplos de elementos metálicos nas condições deste item são:',
  'a) coberturas metálicas sobre o volume a proteger;',
  'b) mastros ou outros elementos condutores salientes nas coberturas;',
  'c) rufos e/ou calhas periféricas de recolhimento de águas pluviais;',
  'd) estruturas metálicas de suporte de envidraçados, para fachadas, acima de 60 m do solo ou de uma superfície horizontal circundante;',
  'e) guarda-corpos, ou outros elementos condutores expostos, para fachadas, acima de 60 m da superfície horizontal circundante;',
  'f) tubos e tanques metálicos construídos em material de espessura igual ou superior à indicada na tabela 4 da NBR5419-ABNT',
];

export const texto5 = [
  'Para os caixilhos metálicos das janelas que se encontram em altura igual ou superior a 60 m e localizados em regiões cujo índice ceráunico Td seja maior que 25, podem ser tomadas medidas alternativas para proporcionar caminhos seguros, excluídas as descidas externas, preferencialmente através das ferragens estruturais eletricamente contínuas das lajes, para equalizar os potenciais que aparecerem no local devidos a correntes elétricas originadas das descargas atmosféricas laterais.',
  '\nAs condições a que devem satisfazer os captores naturais são as seguintes:',
  '\na) a espessura do elemento metálico não deve ser inferior a 0,5 mm ou conforme indicado na tabela 4 da NBR-5419 ABNT, quando for necessário prevenir contra perfurações ou pontos quentes no volume a proteger;',
  ' b) a espessura do elemento metálico pode ser inferior a 2,5 mm, quando não for importante prevenir contra perfurações ou ignição de materiais combustíveis no volume a proteger;',
  'c) o elemento metálico não deve ser revestido de material isolante (não se considera isolante uma camada de pintura de proteção, ou 0,5 mm de asfalto, ou 1 mm de PVC);',
  'd) a continuidade elétrica entre as diversas partes deve ser executada de modo que assegure durabilidade;',
  'e) os elementos não-metálicos acima ou sobre o elemento metálico podem ser excluídos do volume a proteger (em telhas de fibrocimento, o impacto do raio ocorre habitualmente sobre os elementos metálicos de fixação).',
  '\nEstruturas metálicas de torres, postes e mastros, assim como as armaduras de aço interligadas de postes de concreto, constituem descidas naturais até a base das mesmas, dispensando a necessidade de condutores de descida paralelos ao longo da sua extensão.',
  '\nEm construções de alvenaria, ou de qualquer tipo sem armadura metálica interligada, deverá ser implantado um SPDA com descidas externas, que podem ser embutidas. Para diminuir o risco de centelhamento perigoso.',
];

export const textInitial = 'REF.: Laudo técnico de instalações e medições em sistema de SPDA para uso em edificações. Normas técnicas utilizadas: NBR 5419 ABNT (Proteção de estruturas contra descargas atmosféricas); NR-10 (Norma regulamentadora 10 MTE).';
